# SwiftLint Configuration for Votra
# Based on CLAUDE.md guidelines for macOS 26 / Swift 6.2

# Paths to ignore
excluded:
  - DerivedData
  - .build
  - build
  - Pods
  - Packages
  - "*/Generated/*"
  - specs
  - VotraUITests  # XCUIElementQuery uses count instead of isEmpty

# Enabled rules
opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - convenience_type
  - empty_collection_literal
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - file_name
  - first_where
  - flatmap_over_map_reduce
  - force_unwrapping
  - identical_operands
  - implicit_return
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - legacy_random
  - literal_expression_end_indentation
  - modifier_order
  - multiline_arguments
  - multiline_function_chains
  - multiline_parameters
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - private_action
  - private_outlet
  - prohibited_super_call
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  - single_test_class
  - sorted_first_last
  - static_operator
  - toggle_bool
  - trailing_closure
  - type_contents_order
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - vertical_parameter_alignment_on_call
  - yoda_condition

# Disabled rules
disabled_rules:
  - todo
  - trailing_whitespace
  - line_length
  - type_body_length
  - file_length
  - function_body_length
  - nesting

# Rule configurations
force_cast:
  severity: warning

force_try:
  severity: warning

force_unwrapping:
  severity: warning

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 60
    error: 80
  excluded:
    - id
    - x
    - y
    - i
    - j
    - k
    - to

type_name:
  min_length:
    warning: 3
    error: 2
  max_length:
    warning: 50
    error: 60

large_tuple:
  warning: 3
  error: 4

cyclomatic_complexity:
  warning: 15
  error: 25

function_parameter_count:
  warning: 6
  error: 8

type_contents_order:
  order:
    - [case]
    - [type_alias, associated_type]
    - [subtype]
    - [type_property]
    - [instance_property, initializer]
    - [ib_inspectable]
    - [ib_outlet]
    - [type_method]
    - [view_life_cycle_method]
    - [ib_action, ib_segue_action]
    - [other_method]
    - [subscript]
    - [deinitializer]

# Custom rules
custom_rules:
  no_foreground_color:
    name: "Use foregroundStyle"
    regex: "foregroundColor\\("
    message: "Use foregroundStyle() instead of foregroundColor() per CLAUDE.md"
    severity: warning

  no_corner_radius:
    name: "Use clipShape"
    regex: "\\.cornerRadius\\("
    message: "Use clipShape(.rect(cornerRadius:)) instead of cornerRadius() per CLAUDE.md"
    severity: warning

  no_observable_object:
    name: "Use Observable"
    regex: "ObservableObject"
    message: "Use @Observable instead of ObservableObject per CLAUDE.md"
    severity: warning

  no_navigation_view:
    name: "Use NavigationStack"
    regex: "NavigationView\\s*\\{"
    message: "Use NavigationStack instead of NavigationView per CLAUDE.md"
    severity: warning
