name: Bug Report
description: Report a bug or unexpected behavior in Votra
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report this bug! Please fill out the form below.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: I expected...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Instead, what happened was...
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Votra Version
      description: Which version of Votra are you using?
      placeholder: "1.0.0"
    validations:
      required: true

  - type: dropdown
    id: macos
    attributes:
      label: macOS Version
      description: Which version of macOS are you running?
      options:
        - macOS 26.2 (Tahoe)
        - macOS 26.3 (Tahoe)
        - Other (please specify in additional context)
    validations:
      required: true

  - type: dropdown
    id: chip
    attributes:
      label: Apple Silicon Chip
      description: Which Apple Silicon chip is in your Mac?
      options:
        - M1
        - M1 Pro
        - M1 Max
        - M1 Ultra
        - M2
        - M2 Pro
        - M2 Max
        - M2 Ultra
        - M3
        - M3 Pro
        - M3 Max
        - M4
        - M4 Pro
        - M4 Max
        - Other (please specify)
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs
      description: |
        Please copy any relevant log output. You can find logs in Console.app by filtering for "Votra".
      render: shell

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here (screenshots, screen recordings, etc.)
